### ISSUE TITLE
lizmapService: GetPrint() call an undefined method getServiceParameters

### ISSUE THREAD

**Issue by laurentj** [3liz/lizmap-naturaliz-module#1]
Module occtax, `lizmapService.classic.php`, method `GetPrint()`: it calls `getServiceParameters()`. However this method does not exists into the class, nor into the parent class. So it crashes.

**Comment by mdouchin** [comment]
Since a recent change in the map display of results, printing the displayed results with Lizmap is not possible anymore  (vector rendering in the browser) . We will need to migrate the map from OL2 to OL6 to support printing the canvas without the need of a request to QGIS Server.

I close since this issue is not relevant anymore. Thanks anyway for pointing it
